"""
config.py — yt-shorts-autopilot  |  Central Configuration
==========================================================
Loads user settings from  settings.json  (written by setup.py) and falls
back to sensible defaults when the file is absent or a key is missing.

Do NOT edit this file manually — run  setup.py  to change settings.
"""

import json
import random as _random
from pathlib import Path
from datetime import timezone, timedelta

# ── Base directory ────────────────────────────────────────────────────────────
BASE_DIR = Path(__file__).parent

# ── Folder layout ─────────────────────────────────────────────────────────────
QUEUE_DIR   = BASE_DIR / "queue"
DONE_DIR    = BASE_DIR / "done"
PROC_DIR    = BASE_DIR / "processed"
BGM_DIR     = BASE_DIR / "BGM"
LOGO_DIR    = BASE_DIR / "LOGO"
SCRIPTS_DIR = BASE_DIR / "scripts"

# ── Credentials & state files ─────────────────────────────────────────────────
SECRETS_FILE = BASE_DIR / "client_secrets.json"
TOKEN_FILE   = BASE_DIR / "token.json"
LOG_FILE     = BASE_DIR / "upload_log.csv"
APP_LOG      = BASE_DIR / "daily_batch.log"
LAST_RUN     = BASE_DIR / "last_run.txt"

# ── Fixed constants ───────────────────────────────────────────────────────────
PHT    = timezone(timedelta(hours=8))
SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]

DEFAULT_TAGS = [
    "motivation", "shorts", "mindset", "inspiration", "limitlessminds",
    "believe", "blessed", "happy", "success", "selfimprovement",
    "dailymotivation", "motivationalquotes", "wisdom", "growthmindset",
    "uplift", "satisfactionshorts", "youtubeshorts", "motivational",
    "limitless", "mindsetmatters", "positivity", "dailyquotes",
]

# All four corner positions (label, FFmpeg overlay expression)
_ALL_POSITIONS = [
    ("bottom-right", "W-w-15:H-h-15"),
    ("bottom-left",  "15:H-h-15"),
    ("top-left",     "15:15"),
    ("top-right",    "W-w-15:15"),
]

# ─────────────────────────────────────────────────────────────────────────────
#  Load settings.json
# ─────────────────────────────────────────────────────────────────────────────
_SETTINGS_FILE = BASE_DIR / "settings.json"
_s: dict = {}

if _SETTINGS_FILE.exists():
    try:
        with open(_SETTINGS_FILE, encoding="utf-8") as _f:
            _s = json.load(_f)
    except (json.JSONDecodeError, OSError):
        pass   # fall through to defaults

# ─────────────────────────────────────────────────────────────────────────────
#  USER-CONFIGURABLE — populated from settings.json; defaults shown inline
# ─────────────────────────────────────────────────────────────────────────────

# Upload schedule
VIDEOS_PER_RUN: int = _s.get("uploads_per_day", 4)

UPLOAD_TIMES: list[tuple[int, int]] = [
    tuple(t) for t in _s.get("upload_times", [[7, 0], [9, 0], [19, 0], [21, 0]])
]

# Original video audio boost  (setup stores 0–30 as a %; convert to multiplier)
VOLUME_BOOST: float = 1.0 + (_s.get("video_volume_boost_percent", 30) / 100.0)

# Background music
BGM_ENABLED: bool  = _s.get("bgm_enabled", True)
# setup stores 0–100 as an integer level; convert to 0.0–1.0 float for FFmpeg
MUSIC_VOLUME: float = _s.get("bgm_volume", 12) / 100.0

# Watermark
# logo_position:  "bottom-right" | "bottom-left" | "top-left" | "top-right"
#                 | "rotate"  (cycles each upload)
#                 | "random"  (random corner each upload)
WATERMARK_MODE: str = _s.get("logo_position", "rotate")
LOGO_WIDTH: int     = _s.get("logo_width", 130)

# YouTube metadata
CATEGORY_ID: str              = _s.get("category_id", "22")
CHANNEL_HANDLE: str           = _s.get("channel_handle", "@YourChannel")
DEFAULT_TITLE_TEMPLATE: str   = _s.get("default_title_template", "Daily Motivation #{n}")

DEFAULT_DESCRIPTION: str = f"""\
Welcome to Limitless Minds — your daily source of motivation, wisdom, and inspiration. 💡🔥

Every video is crafted to encourage and uplift you to become the best version of yourself.
A limitless mindset starts here. 🧠✨

👍 Like  |  🔔 Subscribe  |  📤 Share if this helped you!

{CHANNEL_HANDLE}

#Shorts #Motivation #LimitlessMinds #MindsetMatters #Inspiration #Success \
#BelieveInYourself #DailyMotivation #MotivationalQuotes #Mindset \
#SelfImprovement #Blessed #Happy #Believe #Wisdom #GrowthMindset \
#Uplift #SatisfactionShorts #YoutubeShorts #Limitless"""


# ─────────────────────────────────────────────────────────────────────────────
#  DERIVED UTILITY  (used by daily_batch.py — do not edit)
# ─────────────────────────────────────────────────────────────────────────────

def get_watermark_coords(upload_index: int) -> tuple[str, str]:
    """
    Return (label, ffmpeg_overlay_coords) based on WATERMARK_MODE.

    Modes
    ─────
    rotate       → cycles  bottom-right → bottom-left → top-left → top-right
    random       → random corner each call
    bottom-right / bottom-left / top-left / top-right → always that corner
    """
    if WATERMARK_MODE == "rotate":
        label, coords = _ALL_POSITIONS[upload_index % len(_ALL_POSITIONS)]
    elif WATERMARK_MODE == "random":
        label, coords = _random.choice(_ALL_POSITIONS)
    else:
        match = next((p for p in _ALL_POSITIONS if p[0] == WATERMARK_MODE), _ALL_POSITIONS[0])
        label, coords = match

    return label, coords
